[project]
name = "realworld-fastapi-htmx"
version = "0.1.0"
description = "RealWorldApp FastAPI + htmx"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt<5.0.0",
    "passlib[bcrypt]>=1.7.4",
    "pyjwt>=2.10.1",
]
